version: '3'
services:
  api:
    image: website_api
    build: .
    ports:
      - "80:8000"
    restart: always
    environment:
    - ENGINE_CONFIGURATION=sqlite:///foo.db
    command: "python /app/main.py"
